### ISSUE TITLE
Bot Commands To Fix

### ISSUE THREAD

**Issue by tintinkung** [ASEAN-Build-The-Earth/Merlion#49]
# command i found thats not working / needs improvement
### 1. `{prefix}`help - command
 https://github.com/ASEAN-Build-The-Earth/Merlion/blob/0b07ebb7e39a1cc64e291b84ec0375d1b720361f/commands/System/help.js#L17
 ```js
Could not send help DM to tintinkung#6084.
 DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (D:\Vscode_Files\Projects\MerlionBot\MerlionMain\Merlion\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\Vscode_Files\Projects\MerlionBot\MerlionMain\Merlion\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async DMChannel.send (D:\Vscode_Files\Projects\MerlionBot\MerlionMain\Merlion\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:172:15) 
{
  method: 'post',
  path: '/channels/897059378694344715/messages',
  code: 50006,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
  ```
---
### 2. `{prefix}`cases - command + Fixed
- nothing seems to work

> <img src="https://user-images.githubusercontent.com/77855014/137151065-0dac966e-c060-4de4-9418-dc4af22b3454.png" alt="mCasesCommand" width="150" height="450">

**Comment by tintinkung** [comment]
**Update:**  Fixed `{prefix}`cases command
at commit https://github.com/ASEAN-Build-The-Earth/Merlion/commit/d5eb4c9e898286e89befdf6bc3f29f74c9ec96dfdf

**Comment by tintinkung** [comment]
`update:` fixed
